
C2_TIMEOUT = 5
C2_HOSTS = [{"ip": "192.168.10.54", "port": 8192}]
C2_ENCRYPTION_KEY = b"nAcvgSoRyvRJGHFG7kgtIolyyVl5ikWqoFwvLWaUKns="
LOGGING_LEVEL = 60

ALLOW_VM = True
ALLOW_DOCKER = True
ALLOW_IF_VM_CHECK_FAILS = False

STARTUP_DELAY = 0
NO_NET_PERSIST = True
